# Generated by Django 3.1.2 on 2020-10-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_auto_20201015_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(choices=[('', 'Select Route Type'), ('One Way', 'One Way'), ('Round Trip', 'Round Trip')], max_length=254),
        ),
    ]
