# Generated by Django 3.1.2 on 2020-10-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0005_routetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.CharField(max_length=254),
        ),
    ]
