# Generated by Django 3.1.2 on 2020-10-16 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20201016_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='route_type',
        ),
    ]
