# Generated by Django 3.1.2 on 2020-10-16 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0007_remove_route_route_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='routes.routetype'),
        ),
    ]
