# Generated by Django 3.1.2 on 2020-11-12 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0008_route_route_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bike_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.biketype'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.routetype'),
        ),
    ]
