# Generated by Django 3.1.2 on 2020-11-17 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0012_auto_20201113_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='map_url',
            field=models.CharField(max_length=1554),
        ),
    ]
