# Generated by Django 3.1.2 on 2020-11-27 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0013_auto_20201117_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='save_routes',
            field=models.ManyToManyField(blank=True, related_name='save_route', to=settings.AUTH_USER_MODEL),
        ),
    ]
