# Generated by Django 3.1.2 on 2020-11-28 00:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('routes', '0016_remove_route_save'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='save',
            field=models.ManyToManyField(blank=True, related_name='save', to=settings.AUTH_USER_MODEL),
        ),
    ]
