# Generated by Django 3.1.2 on 2020-11-26 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20201126_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_user',
        ),
    ]
