# Generated by Django 3.1.2 on 2020-10-26 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201020_1957'),
        ('checkout', '0006_auto_20201025_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='membership',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='OrderLineItem',
        ),
    ]
