# Generated by Django 3.1.2 on 2020-10-26 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201020_1957'),
        ('checkout', '0009_auto_20201026_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership.membership'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
