# Generated by Django 3.1.2 on 2020-10-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20201026_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, editable=False),
        ),
    ]
