# Generated by Django 3.1.2 on 2020-11-06 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_auto_20201106_2019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='original_bag',
            new_name='original_basket',
        ),
    ]
